# Generated by Django 2.0 on 2019-08-08 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='mycourse',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Category'),
            preserve_default=False,
        ),
    ]
