# Generated by Django 2.2.4 on 2019-08-15 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190808_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/avatar/blank.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mycourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Category'),
        ),
    ]
