# Generated by Django 2.2.4 on 2019-08-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190815_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='assets/images/avatar/blank.png', upload_to='profile_pics'),
        ),
    ]
