# Generated by Django 2.2.4 on 2019-08-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190815_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/blank.png', upload_to='profile_pics'),
        ),
    ]
