# Generated by Django 2.2.4 on 2019-08-16 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20190815_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembers',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
